# Generated by Django 5.1 on 2024-12-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_img', models.FileField(max_length=255, null=True, upload_to='E_com_app/')),
                ('pname', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('stock', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
