# Generated by Django 5.1 on 2025-01-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_com_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='c_img',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='E_com_app/'),
        ),
    ]
